/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algs4Practices;

import algs4Practices.Models.Person;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(final String[] args) {

        System.out.println(new App().getGreeting());
        System.out.println("---------------------");
        String hardCodeName = "Manolo";

        if ("manolo" == args[0]) {
            hardCodeName = "Venancio";
        }

        System.out.println("Hello " + args[0] + ", and " + args[1] + " also " + hardCodeName);

        // TODO: Saludar con los nombres recibidos y en el texto del saludo a la terminal

        System.out.println("---------------------");
        final Person person = new Person("Elbert");
        person.talk(args);
    }
}
