/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algs4Practices;

import org.junit.Test;
import static org.junit.Assert.*;

public class RightTriangleTest {
    @Test public void test1() {
        assertTrue(RightTriangle.IsRight(3, 4, 5));
    }

    @Test public void test2() {
        assertTrue(RightTriangle.IsRight(13, 12, 5));
    }

    @Test public void test3() {
        assertFalse(RightTriangle.IsRight(1, 2, 3));
    }

    @Test public void test4() {
        assertFalse(RightTriangle.IsRight(-3, 4, -5));
    }
}
